services:
  traefik:
    image: traefik:v3.1  # Use the latest stable version of Traefik
    container_name: traefik  # The container will always be named 'traefik' for easy reference
    restart: always  # Ensure Traefik automatically restarts on crashes or host reboots
    command:
      - "--configFile=/traefik.yml"  # Use the traefik.yml file for detailed configuration
      - "--log.level=ERROR"  # Set the log level to ERROR directly in the compose file
    ports:
      - "80:80"  # Expose HTTP (port 80)
      - "443:443"  # Expose HTTPS (port 443)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Allows Traefik to communicate with Docker
      - "./letsencrypt:/letsencrypt"  # Directory for Let's Encrypt certificates
      - "./traefik.yml:/traefik.yml"  # Traefik's configuration file
      - "./traefik.log:/var/log/traefik.log"  # Log file for Traefik's activity
    logging:
      driver: "json-file"  # Use Docker's built-in logging driver
      options:
        max-size: "10m"  # Limit log file size to 10 MB
        max-file: "3"  # Keep a maximum of 3 log files
    networks:
      - bckslash  # Connect Traefik to an external network where other services live

networks:
  bckslash:
    external: true  # Ensure the network 'bckslash' exists

